---
namespace: ryan_bell_gea
name: mac_onboarding
version: "1.0.0"
readme: README.md

authors:
  - ryan-bell-gea

description: Collection of macOS automation tools for Ansible. Adapted from geerlingguy.

# Either a single license or a list of licenses for content inside of a collection. Ansible Galaxy currently only
# accepts L(SPDX,https://spdx.org/licenses/) licenses. This key is mutually exclusive with 'license_file'
license:
  - MIT

# A list of tags you want to associate with the collection for indexing/searching. A tag name has the same character
# requirements as 'namespace' and 'name'
tags:
  - mac
  - macos
  - osx
  - homebrew
  - brew
  - workstation
  - dev
  - configure
  - development
  - apple
  - ios
  - macbook
  - imac
  - macmini
  - server
  - infrastructure
  - java

dependencies:
  community.general: ">=3.0.0"

repository: https://github.com/ryan-bell-gea/ansible-collection-mac
documentation: https://github.com/ryan-bell-gea/ansible-collection-mac

build_ignore: []
